# Generated by Django 4.0.1 on 2022-05-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_rename_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='user1',
        ),
    ]
