# Generated by Django 4.0.1 on 2022-05-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_rename_user_user_user1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user1',
        ),
    ]
