# Generated by Django 4.0.1 on 2022-05-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_user_detail_user_login_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='adult',
            field=models.BooleanField(default=False),
        ),
    ]
